### PR TITLE
Exception safety

### LINKED ISSUE #33: Exception Safety
Up to now I've (deliberately) ignored the possibility that our code can panic while being called from C. For example, what would happen if the `PreKeyStore`'s `store()` method panicked [here][1]?

All of our "trampoline" functions need to deal with the possibility of panics. This should mostly be fixed by wrapping calls in a `std::panic::catch_unwind()`, but we may also want to require that *all* trait objects which are passed to C must implement `std::panic::RefUnwindSafe`. 

Alternatively, we could leave them as-is and add some sort of "poisoning" mechanism to the various [`State`][2] types. This would mean the first panic puts a `State` in a "poisoned" state and all further calls result in `InternalError::Unknown` (or some other suitable error).

[1]: https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/ca619c8a95fb3f4f4b2e09b3e32d6f04ae69fd69/libsignal-protocol/src/pre_key_store.rs#L56-L71
[2]: https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/ca619c8a95fb3f4f4b2e09b3e32d6f04ae69fd69/libsignal-protocol/src/pre_key_store.rs#L35

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
This PR tries to make sure a panic emitted from our `extern "C"` trampolines don't accidentally cross the FFI barrier into C.

In particular, this:

- Replaces all `assert!()` calls with a `signal_assert!()` macro that logs the assertions, logs a backtrace, and then return an `InternalError`, in most cases it would be `InternalError::InvalidArgument`.
- Wrap all calls into a user-defined trait object (e.g. `Crypto` or `SessionStore`) with `std::panic::catch_unwind()` so we can log panics and return with an `InternalError::Unknown`
- Adds the `std::panic::RefUnwindSafe` constraint to most user-defined trait objects because they need to be able to handle panics that may happen while operating on the object's internals (e.g. by implementing poisoning like `Mutex` does)

Closes #33.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
@shekohex I *think* I've covered all the places where our Rust code may unwind into C, but it'll require a pretty thorough review. 

I'm also not sure what a failed assertion should do. It's currently logging the error and killing the process, but an alternative would be to return with an `InternalError::Unknown`. I'm a little hesitant to do that though, because it makes it easier to ignore these sorts of fatal errors...

File: libsignal-protocol/src/macros.rs [hunk 1]
```diff
@@ -37,3 +37,53 @@ macro_rules! impl_is_a {
...
+            );
+            ::log::error!("{}", ::failure::Backtrace::new());
+
+            eprintln!(
+                "Aborting because the application reached an unexpected state at {}#{}: {}",
+                file!(),
+                line!(),
+                stringify!($condition)
+            );
+            ::std::process::exit(1);
```
Comment (shekohex) [inline libsignal-protocol/src/macros.rs]: Hmmm, i think it would be better to let that option to the consumer, maybe a simple feature flag `abort-on-ub` enabled by default, so if it's not enabled just return the `InternalError::Unknown`

Comment (Michael-F-Bryan) [reply libsignal-protocol/src/macros.rs]: Looking back at where this macro gets used, it seems it's almost always used to validate arguments at the start of an `unsafe extern "C"` function, so why not **always** return an `InternalError::Argument`?

Originally I was tempted to say the world is in an indeterminate state if we ever get a null pointer and we should crash loudly, but on the other hand, it  could be thought of as just another error due to dodgy input which we can recover from (e.g. by returning `Result<T, E>` or an error code).

**Comment by Michael-F-Bryan** [comment]
Hmm... I just changed the `exit(1)` to a `return InternalError::InvalidArgument` (9f8d85220f607d1624691f5fc2c1b161e4e43c58), but it doesn't look like GitHub knows that commit exists yet :thinking:

**Comment by Michael-F-Bryan** [comment]
Hmm... I just changed the `exit(1)` to a `return InternalError::InvalidArgument` (9f8d85220f607d1624691f5fc2c1b161e4e43c58), but it doesn't look like GitHub knows that commit exists yet :thinking: 

I've also been getting "*You can't comment at this time*" errors a lot tonight.... maybe something's up with GitHub's servers?

File: libsignal-protocol/src/macros.rs (hunk 1 above)
Comment (shekohex) [reply libsignal-protocol/src/macros.rs]: Yeah, i noticed that too, and i don't think it's very bad experience to just crash the whole world, i know it would be better in some cases, but we should better leave that decision for the consumer of the library .
